name: "deploy subjects"
on:
  workflow_dispatch:

jobs:
  build:
    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
    runs-on: [self-hosted, common]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout extensibility actions
        uses: actions/checkout@v2
       
      - name: Validate subjects
        uses: './schema-validator-action'
        with:
          subjects-path: data-extension
      - name: Publish Subjects
        uses: './schema-publisher-action'
        with:
          local-access-key: ${{ secrets.CEPH_BMF.access-key }}
          local-secret-key: ${{ secrets.CEPH_BMF.secret-key }}
          environment: local
          subjects-path: data-extension
